/**
 * Universal Runtime Environment Variable Reader
 * 
 * Supports dual mechanism for reading environment variables:
 * 1. K8s Pod Injection (via OS env -> window.__ENV from env-config.js)
 * 2. Physical .env file (fallback, loaded via Next.js built-in dotenv)
 * 
 * Priority Order:
 *   Browser (Client): window.__ENV -> process.env (build-time inlined) -> fallback
 *   Server (SSR/SSG):  process.env (OS env from K8s Pod / .env file)   -> fallback
 */

declare global {
  interface Window {
    __ENV?: Record<string, string>;
  }
}

/**
 * Get a runtime environment variable with fallback support.
 * 
 * On the **client (browser)**, this reads from `window.__ENV` first
 * (populated by `/env-config.js` generated by `docker-entrypoint.sh`),
 * then falls back to the build-time inlined `process.env` value.
 * 
 * On the **server (Node.js SSR)**, this reads directly from `process.env`
 * which includes K8s-injected OS env variables and `.env` file values.
 * 
 * @param key - The environment variable name (e.g. "NEXT_PUBLIC_API_URL")
 * @param fallback - Default value if the variable is not found anywhere
 * @returns The resolved environment variable value
 */
export function getRuntimeEnv(key: string, fallback: string = ''): string {
  // Client-side (Browser): read from window.__ENV first
  if (typeof window !== 'undefined') {
    const windowValue = (window as Window).__ENV?.[key];
    if (windowValue !== undefined && windowValue !== '') {
      return windowValue;
    }
  }

  // Server-side (Node.js) OR client fallback: read from process.env
  // On server, this reads OS env (K8s injection) or .env file values
  // On client, this reads the build-time inlined value
  const processValue = process.env[key];
  if (processValue !== undefined && processValue !== '') {
    return processValue;
  }

  return fallback;
}
