#!/bin/sh
set -e

ENV_CONFIG_FILE="./public/env-config.js"

echo "==> Preparing runtime environment variables..."

# ============================================================
# 1. LOAD PHYSICAL .env FILE AS FALLBACK (if it exists)
# ============================================================
# Variables already set in the OS environment (from K8s Pod injection)
# will NOT be overwritten by the .env file, because `export` only sets
# variables that are not already defined in the shell environment.
# ============================================================
if [ -f .env ]; then
  echo "    Found physical .env file. Loading as fallback..."
  while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    case "$line" in
      ''|\#*) continue ;;
    esac
    # Extract key and value
    key=$(echo "$line" | cut -d '=' -f 1)
    value=$(echo "$line" | cut -d '=' -f 2-)
    # Only export if the variable is NOT already set in OS env
    if [ -z "$(eval echo \$$key)" ]; then
      export "$key=$value"
      echo "    [.env fallback] $key loaded from file"
    else
      echo "    [K8s injection] $key already set via Pod env, skipping .env"
    fi
  done < .env
else
  echo "    No physical .env file found. Using only OS environment variables."
fi

# ============================================================
# 2. GENERATE public/env-config.js FOR BROWSER (Client-Side)
# ============================================================
# This file is loaded synchronously in <head> by layout.tsx,
# making window.__ENV available before React hydration.
# ============================================================
echo "==> Generating $ENV_CONFIG_FILE for client-side..."

cat > "$ENV_CONFIG_FILE" << EOF
// Auto-generated by docker-entrypoint.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
// DO NOT EDIT — this file is regenerated every time the container starts.
window.__ENV = {
  NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL:-}",
  NEXT_PUBLIC_VILLAGE_ID: "${NEXT_PUBLIC_VILLAGE_ID:-}",
  NEXT_PUBLIC_VILLAGE_NAME: "${NEXT_PUBLIC_VILLAGE_NAME:-}",
  NEXT_PUBLIC_DOMAIN_URL: "${NEXT_PUBLIC_DOMAIN_URL:-}",
  NEXT_PUBLIC_GMAPS_API_KEY: "${NEXT_PUBLIC_GMAPS_API_KEY:-}",
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: "${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID:-}",
  NEXT_PUBLIC_CHATBOT_ID: "${NEXT_PUBLIC_CHATBOT_ID:-}",
  NEXT_PUBLIC_CHATBOT_BASE_URL: "${NEXT_PUBLIC_CHATBOT_BASE_URL:-}",
};
EOF

echo "==> env-config.js successfully created."
echo "==> Starting application..."

# ============================================================
# 3. EXECUTE THE MAIN COMMAND (npm start)
# ============================================================
exec "$@"
